"""Initial tracking migration

Revision ID: e6f8d13b903f
Revises: 
Create Date: 2026-06-24 08:58:44.122827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6f8d13b903f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_logs',
    sa.Column('bus_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_logs_bus_id'), 'location_logs', ['bus_id'], unique=False)
    
    op.create_table('occupancy_logs',
    sa.Column('bus_id', sa.UUID(), nullable=False),
    sa.Column('occupied_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupancy_logs_bus_id'), 'occupancy_logs', ['bus_id'], unique=False)
    
    op.create_table('waiting_logs',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('stop_id', sa.UUID(), nullable=False),
    sa.Column('waiting_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiting_logs_route_id'), 'waiting_logs', ['route_id'], unique=False)
    op.create_index(op.f('ix_waiting_logs_stop_id'), 'waiting_logs', ['stop_id'], unique=False)
    
    op.create_table('eta_logs',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('stop_id', sa.UUID(), nullable=False),
    sa.Column('eta_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eta_logs_route_id'), 'eta_logs', ['route_id'], unique=False)
    op.create_index(op.f('ix_eta_logs_stop_id'), 'eta_logs', ['stop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eta_logs_stop_id'), table_name='eta_logs')
    op.drop_index(op.f('ix_eta_logs_route_id'), table_name='eta_logs')
    op.drop_table('eta_logs')
    op.drop_index(op.f('ix_waiting_logs_stop_id'), table_name='waiting_logs')
    op.drop_index(op.f('ix_waiting_logs_route_id'), table_name='waiting_logs')
    op.drop_table('waiting_logs')
    op.drop_index(op.f('ix_occupancy_logs_bus_id'), table_name='occupancy_logs')
    op.drop_table('occupancy_logs')
    op.drop_index(op.f('ix_location_logs_bus_id'), table_name='location_logs')
    op.drop_table('location_logs')
    # ### end Alembic commands ###
