"""Add schedules and version status

Revision ID: 9499af9cadad
Revises: e6f8d13b903e
Create Date: 2026-06-25 13:24:35.651706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9499af9cadad'
down_revision: Union[str, Sequence[str], None] = 'e6f8d13b903e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_versions', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('stop_versions', sa.Column('geofence_radius_meters', sa.Integer(), nullable=False))
    op.add_column('stop_versions', sa.Column('estimated_arrival_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stop_versions', 'estimated_arrival_time')
    op.drop_column('stop_versions', 'geofence_radius_meters')
    op.drop_column('route_versions', 'status')
    # ### end Alembic commands ###
