"""Change ARRAY to JSON for sqlite compat

Revision ID: fef9c5f36f8c
Revises: 662f51b2d24f
Create Date: 2026-06-25 13:32:46.698131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fef9c5f36f8c'
down_revision: Union[str, Sequence[str], None] = '662f51b2d24f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_schedules', 'recurring_days')
    op.add_column('route_schedules', sa.Column('recurring_days', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route_schedules', 'recurring_days',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=False)
    # ### end Alembic commands ###
